#!/bin/bash
set -euo pipefail

USER="ash"
HOME_DIR="/home/$USER"
START_PATH=$(pwd)

source /mnt/backups/nextcloud/.env
cd ~/nextcloud 
docker-compose up -d

(crontab -l 2>/dev/null; echo "0 * * * * rsync -a --delete /home/ash/nextcloud/ /mnt/backups/nextcloud/") | crontab -

docker exec -i nextcloud-app-1 sh -c "sed -i \"/'trusted_domains' => *array (/a\\
    1 => '192.168.0.57',\\
    2 => '192.168.0.57:8080',\" /var/www/html/config/config.php"
    
speedtest

neofetch

cd $START_PATH
cat postInstall
