#!/bin/bash

dbus-monitor "interface='org.freedesktop.Notifications'" |
while read -r line; do
    # When a Notify method is seen, play a sound
    if echo "$line" | grep -q "method call.*Notify"; then
	mpv /home/ash/.config/swaync/sound.mp3
    fi
done
